namespace: "fortinet"
name: "fortios"
version: "2.3.5"
description: "A collection of Ansible Modules for FortiOS v6"
readme: "README.md"
authors:
    - Frank Shen (@frankshen01)
    - Hongbin Lu (@fgtdev-hblu)
    - Link Zheng (@chillancezen)
    - Jie Xue (@JieX19)
    - Miguel Angel Munoz (@mamunozgonzalez)
    - Nicolas Thomas (@thomnico)
dependencies: {
    "ansible.netcommon": "*"
}
license:
    - "GPL-3.0-or-later"
tags:
    - fortios
    - networking
    - firewall
    - security
    - fortinet
repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection"
documentation: "https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest"
homepage: "https://www.fortinet.com"
issues: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues"
