namespace: "fortinet"
name: "fortios"
version: "1.0.8"
description: "A collection of Ansible Modules for FortiOS v6.0.5"
readme: "README.md"
authors:
    - Frank Shen (@frankshen01)
    - Hongbin Lu (@fgtdev-hblu)
    - Link Zheng (@chillancezen)
    - Jie Xue (@JieX19)
    - Miguel Angel Munoz (@mamunozgonzalez)
    - Nicolas Thomas (@thomnico)
dependencies: { }
license:
    - "MIT"
tags:
    - fortios
    - networking
    - firewall
    - security
    - fortinet
repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/tree/fos_v6.0.5/galaxy_1.0.8"
documentation: "https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-1.0.8"
homepage: "https://www.fortinet.com"
issues: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues"
