- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Schedule group configuration.
    fortios_firewall_schedule_group:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_schedule_group:
        state: "present"
        color: "3"
        member:
         -
            name: "always"
        name: "default_name_6"
