- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Onetime schedule configuration.
    fortios_firewall_schedule_onetime:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_schedule_onetime:
        state: "present"
        color: "3"
        end: "00:00 2021/12/01"
        expiration-days: "5"
        name: "default_name_6"
        start: "00:00 2020/12/01"
