- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure multicast NAT policies.
    fortios_firewall_multicast_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_multicast_policy:
        state: "present"
        action: "accept"
        dnat: "224.2.0.0"
        dstaddr:
         -
            name: "all"
        dstintf: "port2"
        id:  "9"
        logtraffic: "enable"
        protocol: "11"
        snat: "enable"
        snat-ip: "10.210.10.1"
        srcaddr:
         -
            name: "all"
        srcintf: "port1"
        start-port: "17"
        status: "enable"
