- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure IP to MAC address pairs in the IP/MAC binding table.
    fortios_firewall_ipmacbinding_table:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_ipmacbinding_table:
        state: "absent"
        seq-num: "6"
